### ISSUE TITLE
How do I get the robot to move?

### ISSUE THREAD

**Issue by debu00** [or-tal-robotics/mcl_pi_simulation#5]
When I run the command 'roslaunch mcl_pi_move_base.launch', all robots are at rest in the gazebo window, and I get three rviz windows. There are some warnings in the terminal:

[ WARN] [1631700761.364795453, 16.785000000]: MessageFilter [target=map laser_link_KoBot ]: Dropped 100.00% of messages so far. Please turn the [ros.costmap_2d.message_notifier] rosconsole logger to DEBUG for more information.
[ WARN] [1631700761.714298801, 17.077000000]: MessageFilter [target=map laser_link_KoBot2 ]: Dropped 100.00% of messages so far. Please turn the [ros.costmap_2d.message_notifier] rosconsole logger to DEBUG for more information.

How do I get the robot to move like your video?
Thanks

**Comment by TalFeiner** [comment]
Hey, follow the steps that are demonstrated in the linked video [here](https://drive.google.com/file/d/1a8_np5aX-_8IxbPU_oYuCiOld109Cdeb/view?usp=sharing).
Note: each robot have is one rviz window, make sure you know which rviz window belong to each robot. Each rviz window and robot with the same name belong to each other.
For more information please, refer to following links [navigation stack ros](http://wiki.ros.org/navigation?distro=melodic) and [move base](http://wiki.ros.org/move_base?distro=melodic).
 Let me know if it works for you...

> When I run the command 'roslaunch mcl_pi_move_base.launch', all robots are at rest in the gazebo window, and I get three rviz windows. There are some warnings in the terminal:
> 
> [ WARN] [1631700761.364795453, 16.785000000]: MessageFilter [target=map laser_link_KoBot ]: Dropped 100.00% of messages so far. Please turn the [ros.costmap_2d.message_notifier] rosconsole logger to DEBUG for more information.
> [ WARN] [1631700761.714298801, 17.077000000]: MessageFilter [target=map laser_link_KoBot2 ]: Dropped 100.00% of messages so far. Please turn the [ros.costmap_2d.message_notifier] rosconsole logger to DEBUG for more information.
> 
> How do I get the robot to move like your video?
> Thanks

**Comment by debu00** [comment]
Thank you!
That's very helpful.
